In [74]:
print('Hello Jupitor')

Hello Jupitor


In [75]:
import numpy as np
import pandas as pd

In [76]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [77]:
dates = pd.date_range('20130101', periods=6, freq='D')
print(dates)
dates2 = pd.date_range('20130101', periods=6, freq='M')
print(dates2)
dates3 = pd.date_range('20130101', periods=6, freq='Y')
print(dates3)

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')
DatetimeIndex(['2013-01-31', '2013-02-28', '2013-03-31', '2013-04-30',
               '2013-05-31', '2013-06-30'],
              dtype='datetime64[ns]', freq='M')
DatetimeIndex(['2013-12-31', '2014-12-31', '2015-12-31', '2016-12-31',
               '2017-12-31', '2018-12-31'],
              dtype='datetime64[ns]', freq='A-DEC')


In [78]:
# Creating a DataFrame by passing a BumPy array, with a datetime index
# and labeled columns

df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
df

A         B         C         D
2013-01-01 -1.861670  1.507707  0.634822 -1.225244
2013-01-02  1.175150  0.809828 -0.477383  0.410365
2013-01-03  0.572354  0.802708 -0.653188 -0.485505
2013-01-04  0.150041 -0.311701 -0.113150  1.307652
2013-01-05  1.365597  0.677248 -1.353817 -0.444635
2013-01-06 -1.577094 -0.527702  1.976511 -0.465774

In [79]:
# Crearting a DataFrame by passing a dict of objects that can be
# converted to series-like
df2 = pd.DataFrame({'A' : 1.,
                    'B' : pd.Timestamp('20130102'),
                    'C' : pd.Series(1, index=list(range(4)), dtype='float32'),
                    'D' : np.array([3] * 4, dtype='int32'),
                    'E' : pd.Categorical(['test', 'train', 'test', 'train']),
                    'F' : 'foo'})
df2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [80]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [81]:
# Here is how to view the top and bottom rows of the frame :
df.head()

A         B         C         D
2013-01-01 -1.861670  1.507707  0.634822 -1.225244
2013-01-02  1.175150  0.809828 -0.477383  0.410365
2013-01-03  0.572354  0.802708 -0.653188 -0.485505
2013-01-04  0.150041 -0.311701 -0.113150  1.307652
2013-01-05  1.365597  0.677248 -1.353817 -0.444635

In [82]:
df.tail()

A         B         C         D
2013-01-02  1.175150  0.809828 -0.477383  0.410365
2013-01-03  0.572354  0.802708 -0.653188 -0.485505
2013-01-04  0.150041 -0.311701 -0.113150  1.307652
2013-01-05  1.365597  0.677248 -1.353817 -0.444635
2013-01-06 -1.577094 -0.527702  1.976511 -0.465774

In [83]:
df2.index

Int64Index([0, 1, 2, 3], dtype='int64')

In [84]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [85]:
'''
DataFrame.to_numpy() gives a NumPy representation of the underlying data
Note that this can be ad expensive operation when your DataFrame has columns with different
dtypes, which comes down to a fundemental difference between pandas and NumPy
: Numpy arrays have one dtype for the entire array, whlie pandas DataFrames have one dtype
per column. when you call DataFrame.to_numpy(), pandas will find the Numpy dtype that can hold all of the dtypes in the DataFrame. This may end up being 'object', which requires
casting every value to a Python objent
'''

df.to_numpy()

array([[-1.86167025,  1.50770703,  0.63482174, -1.22524424],
       [ 1.17515042,  0.80982812, -0.47738286,  0.41036534],
       [ 0.57235425,  0.8027078 , -0.65318808, -0.48550491],
       [ 0.15004124, -0.31170079, -0.11314963,  1.30765238],
       [ 1.36559658,  0.6772482 , -1.35381735, -0.4446353 ],
       [-1.57709439, -0.52770209,  1.97651075, -0.4657744 ]])

In [86]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [87]:
# summary of data
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.029270  0.493015  0.002299 -0.150524
std    1.381581  0.768017  1.167025  0.882496
min   -1.861670 -0.527702 -1.353817 -1.225244
25%   -1.145310 -0.064464 -0.609237 -0.480572
50%    0.361198  0.739978 -0.295266 -0.455205
75%    1.024451  0.808048  0.447829  0.196615
max    1.365597  1.507707  1.976511  1.307652

In [88]:
# Transpose
print(df.to_numpy())
df.T

[[-1.86167025  1.50770703  0.63482174 -1.22524424]
 [ 1.17515042  0.80982812 -0.47738286  0.41036534]
 [ 0.57235425  0.8027078  -0.65318808 -0.48550491]
 [ 0.15004124 -0.31170079 -0.11314963  1.30765238]
 [ 1.36559658  0.6772482  -1.35381735 -0.4446353 ]
 [-1.57709439 -0.52770209  1.97651075 -0.4657744 ]]


2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A   -1.861670    1.175150    0.572354    0.150041    1.365597   -1.577094
B    1.507707    0.809828    0.802708   -0.311701    0.677248   -0.527702
C    0.634822   -0.477383   -0.653188   -0.113150   -1.353817    1.976511
D   -1.225244    0.410365   -0.485505    1.307652   -0.444635   -0.465774

In [89]:
# column명을 기준으로 sort
df.sort_index(axis=1, ascending=True)

A         B         C         D
2013-01-01 -1.861670  1.507707  0.634822 -1.225244
2013-01-02  1.175150  0.809828 -0.477383  0.410365
2013-01-03  0.572354  0.802708 -0.653188 -0.485505
2013-01-04  0.150041 -0.311701 -0.113150  1.307652
2013-01-05  1.365597  0.677248 -1.353817 -0.444635
2013-01-06 -1.577094 -0.527702  1.976511 -0.465774

In [90]:
# B column을 기준으로 sort
df.sort_values(by='B', ascending=False)

A         B         C         D
2013-01-01 -1.861670  1.507707  0.634822 -1.225244
2013-01-02  1.175150  0.809828 -0.477383  0.410365
2013-01-03  0.572354  0.802708 -0.653188 -0.485505
2013-01-05  1.365597  0.677248 -1.353817 -0.444635
2013-01-04  0.150041 -0.311701 -0.113150  1.307652
2013-01-06 -1.577094 -0.527702  1.976511 -0.465774

In [91]:
#################################################
# Selection
#################################################

# selection by index (row)

df['A']

2013-01-01   -1.861670
2013-01-02    1.175150
2013-01-03    0.572354
2013-01-04    0.150041
2013-01-05    1.365597
2013-01-06   -1.577094
Freq: D, Name: A, dtype: float64

In [92]:
df[0:3]

A         B         C         D
2013-01-01 -1.861670  1.507707  0.634822 -1.225244
2013-01-02  1.175150  0.809828 -0.477383  0.410365
2013-01-03  0.572354  0.802708 -0.653188 -0.485505

In [93]:
df['20130102':'20130104']

A         B         C         D
2013-01-02  1.175150  0.809828 -0.477383  0.410365
2013-01-03  0.572354  0.802708 -0.653188 -0.485505
2013-01-04  0.150041 -0.311701 -0.113150  1.307652

In [94]:
# selection by label (column)

# dates = ['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04', '2013-01-05', '2013-01-06']
# 2013-01-01 row값을 label을 기준으로 출력
df.loc[dates[0]]

A   -1.861670
B    1.507707
C    0.634822
D   -1.225244
Name: 2013-01-01 00:00:00, dtype: float64

In [95]:
# 전체 row중 'A', 'B' 라벨만을 출력
df.loc[:, ['A', 'B']]

A         B
2013-01-01 -1.861670  1.507707
2013-01-02  1.175150  0.809828
2013-01-03  0.572354  0.802708
2013-01-04  0.150041 -0.311701
2013-01-05  1.365597  0.677248
2013-01-06 -1.577094 -0.527702

In [96]:
df.loc['20130102':'20130104', ['A', 'B']]

A         B
2013-01-02  1.175150  0.809828
2013-01-03  0.572354  0.802708
2013-01-04  0.150041 -0.311701

In [97]:
# for getting a scalar value :
df.loc[dates[0], 'A']

-1.8616702538366903

In [98]:
######################################################
# Selection by position
######################################################

# index locating? 인듯
print(df)
df.iloc[3]

A         B         C         D
2013-01-01 -1.861670  1.507707  0.634822 -1.225244
2013-01-02  1.175150  0.809828 -0.477383  0.410365
2013-01-03  0.572354  0.802708 -0.653188 -0.485505
2013-01-04  0.150041 -0.311701 -0.113150  1.307652
2013-01-05  1.365597  0.677248 -1.353817 -0.444635
2013-01-06 -1.577094 -0.527702  1.976511 -0.465774


A    0.150041
B   -0.311701
C   -0.113150
D    1.307652
Name: 2013-01-04 00:00:00, dtype: float64

In [99]:
df.iloc[1:3, :]

A         B         C         D
2013-01-02  1.175150  0.809828 -0.477383  0.410365
2013-01-03  0.572354  0.802708 -0.653188 -0.485505

In [100]:
df.iloc[[1, 2, 4], [0, 2]]

A         C
2013-01-02  1.175150 -0.477383
2013-01-03  0.572354 -0.653188
2013-01-05  1.365597 -1.353817

In [101]:
# iloc[1, 1], iat[1, 1] 의 결과는 같지만
# iat가 개별 값에 접근할 떄는 더 빠르다

df.iloc[1, 1]

0.80982811730012

In [102]:
df.iat[1, 1]

0.80982811730012

In [103]:
######################################################
# boolean indexing
######################################################

df[df < 0]

A         B         C         D
2013-01-01 -1.861670       NaN       NaN -1.225244
2013-01-02       NaN       NaN -0.477383       NaN
2013-01-03       NaN       NaN -0.653188 -0.485505
2013-01-04       NaN -0.311701 -0.113150       NaN
2013-01-05       NaN       NaN -1.353817 -0.444635
2013-01-06 -1.577094 -0.527702       NaN -0.465774

In [104]:
df[df > 0]

A         B         C         D
2013-01-01       NaN  1.507707  0.634822       NaN
2013-01-02  1.175150  0.809828       NaN  0.410365
2013-01-03  0.572354  0.802708       NaN       NaN
2013-01-04  0.150041       NaN       NaN  1.307652
2013-01-05  1.365597  0.677248       NaN       NaN
2013-01-06       NaN       NaN  1.976511       NaN

In [105]:
# column의 추가

df2 = df.copy()
df2['E'] = ['one', 'one', 'two', 'three', 'four', 'three']
df2

A         B         C         D      E
2013-01-01 -1.861670  1.507707  0.634822 -1.225244    one
2013-01-02  1.175150  0.809828 -0.477383  0.410365    one
2013-01-03  0.572354  0.802708 -0.653188 -0.485505    two
2013-01-04  0.150041 -0.311701 -0.113150  1.307652  three
2013-01-05  1.365597  0.677248 -1.353817 -0.444635   four
2013-01-06 -1.577094 -0.527702  1.976511 -0.465774  three

In [106]:
df[df['A'] > 0]

A         B         C         D
2013-01-02  1.175150  0.809828 -0.477383  0.410365
2013-01-03  0.572354  0.802708 -0.653188 -0.485505
2013-01-04  0.150041 -0.311701 -0.113150  1.307652
2013-01-05  1.365597  0.677248 -1.353817 -0.444635

In [107]:
df2[df2['E'].isin(['two', 'four'])]

A         B         C         D     E
2013-01-03  0.572354  0.802708 -0.653188 -0.485505   two
2013-01-05  1.365597  0.677248 -1.353817 -0.444635  four

In [111]:
######################################################
# pandas primarily uses the value 'np.nan' to represent
# missing data. It is by default not included in computations.
# See the missing data selection
######################################################

# reindexing allows you to change / add / delete the index on a 
# specified axis. This returns a copy of the data

df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ['E'])
df1.loc[dates[0]:dates[1], 'E'] = 1
df1

A         B         C         D    E
2013-01-01 -1.861670  1.507707  0.634822 -1.225244  1.0
2013-01-02  1.175150  0.809828 -0.477383  0.410365  1.0
2013-01-03  0.572354  0.802708 -0.653188 -0.485505  NaN
2013-01-04  0.150041 -0.311701 -0.113150  1.307652  NaN

In [112]:
# to drop any rows that have missing data
df1.dropna(how='any')

A         B         C         D    E
2013-01-01 -1.86167  1.507707  0.634822 -1.225244  1.0
2013-01-02  1.17515  0.809828 -0.477383  0.410365  1.0

In [113]:
# filling missing data
df1.fillna(value=5)

A         B         C         D    E
2013-01-01 -1.861670  1.507707  0.634822 -1.225244  1.0
2013-01-02  1.175150  0.809828 -0.477383  0.410365  1.0
2013-01-03  0.572354  0.802708 -0.653188 -0.485505  5.0
2013-01-04  0.150041 -0.311701 -0.113150  1.307652  5.0

In [114]:
# to get the boolean mask where values are nan
pd.isna(df1)

A      B      C      D      E
2013-01-01  False  False  False  False  False
2013-01-02  False  False  False  False  False
2013-01-03  False  False  False  False   True
2013-01-04  False  False  False  False   True

In [117]:
######################################################
# Operation
######################################################

# column 기준
df.mean(False)

A   -0.029270
B    0.493015
C    0.002299
D   -0.150524
dtype: float64

In [118]:
# row 기준 row기준 = False 가 default 인듯
df.mean(True)

2013-01-01   -0.236096
2013-01-02    0.479490
2013-01-03    0.059092
2013-01-04    0.258211
2013-01-05    0.061098
2013-01-06   -0.148515
Freq: D, dtype: float64

In [124]:
# shift

s = pd.Series([1, 3, 5, np.nan, 6, 8], index=dates).shift(1)
s

2013-01-01    NaN
2013-01-02    1.0
2013-01-03    3.0
2013-01-04    5.0
2013-01-05    NaN
2013-01-06    6.0
Freq: D, dtype: float64

In [125]:
df.sub(s, axis='index')

A         B         C         D
2013-01-01       NaN       NaN       NaN       NaN
2013-01-02  0.175150 -0.190172 -1.477383 -0.589635
2013-01-03 -2.427646 -2.197292 -3.653188 -3.485505
2013-01-04 -4.849959 -5.311701 -5.113150 -3.692348
2013-01-05       NaN       NaN       NaN       NaN
2013-01-06 -7.577094 -6.527702 -4.023489 -6.465774

In [130]:
df.sub(s, axis='index')

A         B         C         D
2013-01-01       NaN       NaN       NaN       NaN
2013-01-02  0.175150 -0.190172 -1.477383 -0.589635
2013-01-03 -2.427646 -2.197292 -3.653188 -3.485505
2013-01-04 -4.849959 -5.311701 -5.113150 -3.692348
2013-01-05       NaN       NaN       NaN       NaN
2013-01-06 -7.577094 -6.527702 -4.023489 -6.465774

In [132]:
# ######################################################
# Applying function to the data :
######################################################
print(df)
# column별로 cumulative sum
df.apply(np.cumsum)

A         B         C         D
2013-01-01 -1.861670  1.507707  0.634822 -1.225244
2013-01-02  1.175150  0.809828 -0.477383  0.410365
2013-01-03  0.572354  0.802708 -0.653188 -0.485505
2013-01-04  0.150041 -0.311701 -0.113150  1.307652
2013-01-05  1.365597  0.677248 -1.353817 -0.444635
2013-01-06 -1.577094 -0.527702  1.976511 -0.465774


A         B         C         D
2013-01-01 -1.861670  1.507707  0.634822 -1.225244
2013-01-02 -0.686520  2.317535  0.157439 -0.814879
2013-01-03 -0.114166  3.120243 -0.495749 -1.300384
2013-01-04  0.035876  2.808542 -0.608899  0.007269
2013-01-05  1.401472  3.485790 -1.962716 -0.437367
2013-01-06 -0.175622  2.958088  0.013795 -0.903141

In [134]:
######################################################
# Histogramming
######################################################

s = pd.Series(np.random.randint(0, 7, size=10))
s

0    3
1    3
2    2
3    4
4    0
5    2
6    4
7    1
8    1
9    1
dtype: int64

In [138]:
s.value_counts()

1    3
4    2
3    2
2    2
0    1
dtype: int64

In [136]:
s.value_counts().sort_index()

0    1
1    3
2    2
3    2
4    2
dtype: int64

In [150]:
s = pd.Series(['apple', 'Banan', 'Carrot', 'Aaba', 'Bcad', np.nan, 'CABA'])
s.str.lower()

0     apple
1     banan
2    carrot
3      aaba
4      bcad
5       NaN
6      caba
dtype: object