In [4]:
print('Hello Jupitor')

Hello Jupitor


In [6]:
import numpy as np
import pandas as pd

In [8]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [10]:
dates = pd.date_range('20130101', periods=6, freq='D')
print(dates)
dates2 = pd.date_range('20130101', periods=6, freq='M')
print(dates2)
dates3 = pd.date_range('20130101', periods=6, freq='Y')
print(dates3)

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')
DatetimeIndex(['2013-01-31', '2013-02-28', '2013-03-31', '2013-04-30',
               '2013-05-31', '2013-06-30'],
              dtype='datetime64[ns]', freq='M')
DatetimeIndex(['2013-12-31', '2014-12-31', '2015-12-31', '2016-12-31',
               '2017-12-31', '2018-12-31'],
              dtype='datetime64[ns]', freq='A-DEC')


In [12]:
# Creating a DataFrame by passing a BumPy array, with a datetime index
# and labeled columns

df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
df

A         B         C         D
2013-01-01  0.693891  0.342582  0.842040 -0.614046
2013-01-02 -0.380125  1.286044 -1.826363 -1.759597
2013-01-03  0.575377 -1.030226 -1.458529 -0.229265
2013-01-04 -0.198816  0.151591  0.868986  0.046130
2013-01-05 -1.426182 -0.194032  1.376995  1.332500
2013-01-06 -1.263439 -0.591865  1.479771  0.658840

In [14]:
# Crearting a DataFrame by passing a dict of objects that can be
# converted to series-like
df2 = pd.DataFrame({'A' : 1.,
                    'B' : pd.Timestamp('20130102'),
                    'C' : pd.Series(1, index=list(range(4)), dtype='float32'),
                    'D' : np.array([3] * 4, dtype='int32'),
                    'E' : pd.Categorical(['test', 'train', 'test', 'train']),
                    'F' : 'foo'})
df2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [16]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [18]:
# Here is how to view the top and bottom rows of the frame :
df.head()

A         B         C         D
2013-01-01  0.693891  0.342582  0.842040 -0.614046
2013-01-02 -0.380125  1.286044 -1.826363 -1.759597
2013-01-03  0.575377 -1.030226 -1.458529 -0.229265
2013-01-04 -0.198816  0.151591  0.868986  0.046130
2013-01-05 -1.426182 -0.194032  1.376995  1.332500

In [20]:
df.tail()

A         B         C         D
2013-01-02 -0.380125  1.286044 -1.826363 -1.759597
2013-01-03  0.575377 -1.030226 -1.458529 -0.229265
2013-01-04 -0.198816  0.151591  0.868986  0.046130
2013-01-05 -1.426182 -0.194032  1.376995  1.332500
2013-01-06 -1.263439 -0.591865  1.479771  0.658840

In [22]:
df2.index

Int64Index([0, 1, 2, 3], dtype='int64')

In [24]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [26]:
'''
DataFrame.to_numpy() gives a NumPy representation of the underlying data
Note that this can be ad expensive operation when your DataFrame has columns with different
dtypes, which comes down to a fundemental difference between pandas and NumPy
: Numpy arrays have one dtype for the entire array, whlie pandas DataFrames have one dtype
per column. when you call DataFrame.to_numpy(), pandas will find the Numpy dtype that can hold all of the dtypes in the DataFrame. This may end up being 'object', which requires
casting every value to a Python objent
'''

df.to_numpy()

array([[ 0.69389058,  0.34258175,  0.8420397 , -0.61404588],
       [-0.38012533,  1.28604429, -1.82636254, -1.75959688],
       [ 0.57537682, -1.03022582, -1.45852874, -0.2292651 ],
       [-0.19881581,  0.15159082,  0.86898623,  0.04612965],
       [-1.42618157, -0.19403242,  1.3769953 ,  1.33249996],
       [-1.26343907, -0.5918651 ,  1.4797715 ,  0.6588401 ]])

In [28]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [30]:
# summary of data
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.333216 -0.005984  0.213817 -0.094240
std    0.890016  0.805401  1.465511  1.066233
min   -1.426182 -1.030226 -1.826363 -1.759597
25%   -1.042611 -0.492407 -0.883387 -0.517851
50%   -0.289471 -0.021221  0.855513 -0.091568
75%    0.381829  0.294834  1.249993  0.505662
max    0.693891  1.286044  1.479771  1.332500

In [32]:
# Transpose
print(df.to_numpy())
df.T

[[ 0.69389058  0.34258175  0.8420397  -0.61404588]
 [-0.38012533  1.28604429 -1.82636254 -1.75959688]
 [ 0.57537682 -1.03022582 -1.45852874 -0.2292651 ]
 [-0.19881581  0.15159082  0.86898623  0.04612965]
 [-1.42618157 -0.19403242  1.3769953   1.33249996]
 [-1.26343907 -0.5918651   1.4797715   0.6588401 ]]


2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    0.693891   -0.380125    0.575377   -0.198816   -1.426182   -1.263439
B    0.342582    1.286044   -1.030226    0.151591   -0.194032   -0.591865
C    0.842040   -1.826363   -1.458529    0.868986    1.376995    1.479771
D   -0.614046   -1.759597   -0.229265    0.046130    1.332500    0.658840

In [34]:
# column명을 기준으로 sort
df.sort_index(axis=1, ascending=True)

A         B         C         D
2013-01-01  0.693891  0.342582  0.842040 -0.614046
2013-01-02 -0.380125  1.286044 -1.826363 -1.759597
2013-01-03  0.575377 -1.030226 -1.458529 -0.229265
2013-01-04 -0.198816  0.151591  0.868986  0.046130
2013-01-05 -1.426182 -0.194032  1.376995  1.332500
2013-01-06 -1.263439 -0.591865  1.479771  0.658840

In [36]:
# B column을 기준으로 sort
df.sort_values(by='B', ascending=False)

A         B         C         D
2013-01-02 -0.380125  1.286044 -1.826363 -1.759597
2013-01-01  0.693891  0.342582  0.842040 -0.614046
2013-01-04 -0.198816  0.151591  0.868986  0.046130
2013-01-05 -1.426182 -0.194032  1.376995  1.332500
2013-01-06 -1.263439 -0.591865  1.479771  0.658840
2013-01-03  0.575377 -1.030226 -1.458529 -0.229265

In [38]:
#################################################
# Selection
#################################################

# selection by index (row)

df['A']

2013-01-01    0.693891
2013-01-02   -0.380125
2013-01-03    0.575377
2013-01-04   -0.198816
2013-01-05   -1.426182
2013-01-06   -1.263439
Freq: D, Name: A, dtype: float64

In [40]:
df[0:3]

A         B         C         D
2013-01-01  0.693891  0.342582  0.842040 -0.614046
2013-01-02 -0.380125  1.286044 -1.826363 -1.759597
2013-01-03  0.575377 -1.030226 -1.458529 -0.229265

In [42]:
df['20130102':'20130104']

A         B         C         D
2013-01-02 -0.380125  1.286044 -1.826363 -1.759597
2013-01-03  0.575377 -1.030226 -1.458529 -0.229265
2013-01-04 -0.198816  0.151591  0.868986  0.046130

In [44]:
# selection by label (column)

# dates = ['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04', '2013-01-05', '2013-01-06']
# 2013-01-01 row값을 label을 기준으로 출력
df.loc[dates[0]]

A    0.693891
B    0.342582
C    0.842040
D   -0.614046
Name: 2013-01-01 00:00:00, dtype: float64

In [46]:
# 전체 row중 'A', 'B' 라벨만을 출력
df.loc[:, ['A', 'B']]

A         B
2013-01-01  0.693891  0.342582
2013-01-02 -0.380125  1.286044
2013-01-03  0.575377 -1.030226
2013-01-04 -0.198816  0.151591
2013-01-05 -1.426182 -0.194032
2013-01-06 -1.263439 -0.591865

In [48]:
df.loc['20130102':'20130104', ['A', 'B']]

A         B
2013-01-02 -0.380125  1.286044
2013-01-03  0.575377 -1.030226
2013-01-04 -0.198816  0.151591

In [50]:
# for getting a scalar value :
df.loc[dates[0], 'A']

0.6938905753543304

In [52]:
######################################################
# Selection by position
######################################################

# index locating? 인듯
print(df)
df.iloc[3]

A         B         C         D
2013-01-01  0.693891  0.342582  0.842040 -0.614046
2013-01-02 -0.380125  1.286044 -1.826363 -1.759597
2013-01-03  0.575377 -1.030226 -1.458529 -0.229265
2013-01-04 -0.198816  0.151591  0.868986  0.046130
2013-01-05 -1.426182 -0.194032  1.376995  1.332500
2013-01-06 -1.263439 -0.591865  1.479771  0.658840


A   -0.198816
B    0.151591
C    0.868986
D    0.046130
Name: 2013-01-04 00:00:00, dtype: float64

In [54]:
df.iloc[1:3, :]

A         B         C         D
2013-01-02 -0.380125  1.286044 -1.826363 -1.759597
2013-01-03  0.575377 -1.030226 -1.458529 -0.229265

In [56]:
df.iloc[[1, 2, 4], [0, 2]]

A         C
2013-01-02 -0.380125 -1.826363
2013-01-03  0.575377 -1.458529
2013-01-05 -1.426182  1.376995

In [58]:
# iloc[1, 1], iat[1, 1] 의 결과는 같지만
# iat가 개별 값에 접근할 떄는 더 빠르다

df.iloc[1, 1]

1.2860442931958265

In [60]:
df.iat[1, 1]

1.2860442931958265

In [62]:
######################################################
# boolean indexing
######################################################

df[df < 0]

A         B         C         D
2013-01-01       NaN       NaN       NaN -0.614046
2013-01-02 -0.380125       NaN -1.826363 -1.759597
2013-01-03       NaN -1.030226 -1.458529 -0.229265
2013-01-04 -0.198816       NaN       NaN       NaN
2013-01-05 -1.426182 -0.194032       NaN       NaN
2013-01-06 -1.263439 -0.591865       NaN       NaN

In [64]:
df[df > 0]

A         B         C        D
2013-01-01  0.693891  0.342582  0.842040      NaN
2013-01-02       NaN  1.286044       NaN      NaN
2013-01-03  0.575377       NaN       NaN      NaN
2013-01-04       NaN  0.151591  0.868986  0.04613
2013-01-05       NaN       NaN  1.376995  1.33250
2013-01-06       NaN       NaN  1.479771  0.65884

In [66]:
# column의 추가

df2 = df.copy()
df2['E'] = ['one', 'one', 'two', 'three', 'four', 'three']
df2

A         B         C         D      E
2013-01-01  0.693891  0.342582  0.842040 -0.614046    one
2013-01-02 -0.380125  1.286044 -1.826363 -1.759597    one
2013-01-03  0.575377 -1.030226 -1.458529 -0.229265    two
2013-01-04 -0.198816  0.151591  0.868986  0.046130  three
2013-01-05 -1.426182 -0.194032  1.376995  1.332500   four
2013-01-06 -1.263439 -0.591865  1.479771  0.658840  three

In [68]:
df[df['A'] > 0]

A         B         C         D
2013-01-01  0.693891  0.342582  0.842040 -0.614046
2013-01-03  0.575377 -1.030226 -1.458529 -0.229265

In [70]:
df2[df2['E'].isin(['two', 'four'])]

A         B         C         D     E
2013-01-03  0.575377 -1.030226 -1.458529 -0.229265   two
2013-01-05 -1.426182 -0.194032  1.376995  1.332500  four

In [72]:
######################################################
# pandas primarily uses the value 'np.nan' to represent
# missing data. It is by default not included in computations.
# See the missing data selection
######################################################

# reindexing allows you to change / add / delete the index on a 
# specified axis. This returns a copy of the data

df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ['E'])
df1.loc[dates[0]:dates[1], 'E'] = 1
df1

A         B         C         D    E
2013-01-01  0.693891  0.342582  0.842040 -0.614046  1.0
2013-01-02 -0.380125  1.286044 -1.826363 -1.759597  1.0
2013-01-03  0.575377 -1.030226 -1.458529 -0.229265  NaN
2013-01-04 -0.198816  0.151591  0.868986  0.046130  NaN

In [74]:
# to drop any rows that have missing data
df1.dropna(how='any')

A         B         C         D    E
2013-01-01  0.693891  0.342582  0.842040 -0.614046  1.0
2013-01-02 -0.380125  1.286044 -1.826363 -1.759597  1.0

In [76]:
# filling missing data
df1.fillna(value=5)

A         B         C         D    E
2013-01-01  0.693891  0.342582  0.842040 -0.614046  1.0
2013-01-02 -0.380125  1.286044 -1.826363 -1.759597  1.0
2013-01-03  0.575377 -1.030226 -1.458529 -0.229265  5.0
2013-01-04 -0.198816  0.151591  0.868986  0.046130  5.0

In [78]:
# to get the boolean mask where values are nan
pd.isna(df1)

A      B      C      D      E
2013-01-01  False  False  False  False  False
2013-01-02  False  False  False  False  False
2013-01-03  False  False  False  False   True
2013-01-04  False  False  False  False   True

In [80]:
######################################################
# Operation
######################################################

# column 기준
df.mean(False)

A   -0.333216
B   -0.005984
C    0.213817
D   -0.094240
dtype: float64

In [82]:
# row 기준 row기준 = False 가 default 인듯
df.mean(True)

2013-01-01    0.316117
2013-01-02   -0.670010
2013-01-03   -0.535661
2013-01-04    0.216973
2013-01-05    0.272320
2013-01-06    0.070827
Freq: D, dtype: float64

In [84]:
# shift

s = pd.Series([1, 3, 5, np.nan, 6, 8], index=dates).shift(1)
s

2013-01-01    NaN
2013-01-02    1.0
2013-01-03    3.0
2013-01-04    5.0
2013-01-05    NaN
2013-01-06    6.0
Freq: D, dtype: float64

In [86]:
df.sub(s, axis='index')

A         B         C         D
2013-01-01       NaN       NaN       NaN       NaN
2013-01-02 -1.380125  0.286044 -2.826363 -2.759597
2013-01-03 -2.424623 -4.030226 -4.458529 -3.229265
2013-01-04 -5.198816 -4.848409 -4.131014 -4.953870
2013-01-05       NaN       NaN       NaN       NaN
2013-01-06 -7.263439 -6.591865 -4.520229 -5.341160

In [88]:
df.sub(s, axis='index')

A         B         C         D
2013-01-01       NaN       NaN       NaN       NaN
2013-01-02 -1.380125  0.286044 -2.826363 -2.759597
2013-01-03 -2.424623 -4.030226 -4.458529 -3.229265
2013-01-04 -5.198816 -4.848409 -4.131014 -4.953870
2013-01-05       NaN       NaN       NaN       NaN
2013-01-06 -7.263439 -6.591865 -4.520229 -5.341160

In [90]:
# ######################################################
# Applying function to the data :
######################################################
print(df)
# column별로 cumulative sum
df.apply(np.cumsum)

A         B         C         D
2013-01-01  0.693891  0.342582  0.842040 -0.614046
2013-01-02 -0.380125  1.286044 -1.826363 -1.759597
2013-01-03  0.575377 -1.030226 -1.458529 -0.229265
2013-01-04 -0.198816  0.151591  0.868986  0.046130
2013-01-05 -1.426182 -0.194032  1.376995  1.332500
2013-01-06 -1.263439 -0.591865  1.479771  0.658840


A         B         C         D
2013-01-01  0.693891  0.342582  0.842040 -0.614046
2013-01-02  0.313765  1.628626 -0.984323 -2.373643
2013-01-03  0.889142  0.598400 -2.442852 -2.602908
2013-01-04  0.690326  0.749991 -1.573865 -2.556778
2013-01-05 -0.735855  0.555959 -0.196870 -1.224278
2013-01-06 -1.999294 -0.035906  1.282901 -0.565438

In [92]:
######################################################
# Histogramming
######################################################

s = pd.Series(np.random.randint(0, 7, size=10))
s

0    1
1    5
2    0
3    0
4    6
5    6
6    0
7    6
8    4
9    2
dtype: int64

In [94]:
s.value_counts()

6    3
0    3
5    1
4    1
2    1
1    1
dtype: int64

In [96]:
s.value_counts().sort_index()

Aaba      1
Banan     1
Bcad      1
CABA      1
Carrot    1
apple     1
dtype: int64

In [98]:
s = pd.Series(['apple', 'Banan', 'Carrot', 'Aaba', 'Bcad', np.nan, 'CABA'])
s.str.lower()

0     apple
1     banan
2    carrot
3      aaba
4      bcad
5       NaN
6      caba
dtype: object

In [100]:
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [102]:
############################################
# Setting 
############################################
# Setting a new column automatically aligns the data by the indices

s1 = pd.Series([1, 2, 3, 4, 5, 6], index=pd.date_range('20130102', periods=6))
s1

2013-01-02    1
2013-01-03    2
2013-01-04    3
2013-01-05    4
2013-01-06    5
2013-01-07    6
Freq: D, dtype: int64

In [104]:
df

A         B         C         D
2013-01-01  0.693891  0.342582  0.842040 -0.614046
2013-01-02 -0.380125  1.286044 -1.826363 -1.759597
2013-01-03  0.575377 -1.030226 -1.458529 -0.229265
2013-01-04 -0.198816  0.151591  0.868986  0.046130
2013-01-05 -1.426182 -0.194032  1.376995  1.332500
2013-01-06 -1.263439 -0.591865  1.479771  0.658840

In [106]:
# df에 F column으로 s1을 추가


In [108]:
# 1월2일부터 해당 값이 자동으로 setting되어 입력된다

df['F'] = s1
df

A         B         C         D    F
2013-01-01  0.000000  0.342582  0.842040 -0.614046  NaN
2013-01-02 -0.380125  1.286044 -1.826363 -1.759597  1.0
2013-01-03  0.575377 -1.030226 -1.458529 -0.229265  2.0
2013-01-04 -0.198816  0.151591  0.868986  0.046130  3.0
2013-01-05 -1.426182 -0.194032  1.376995  1.332500  4.0
2013-01-06 -1.263439 -0.591865  1.479771  0.658840  5.0

In [110]:
# setting values by label
df.at[dates[0], 'A'] = 0
df

A         B         C         D    F
2013-01-01  0.000000  0.000000  0.842040 -0.614046  NaN
2013-01-02 -0.380125  1.286044 -1.826363 -1.759597  1.0
2013-01-03  0.575377 -1.030226 -1.458529 -0.229265  2.0
2013-01-04 -0.198816  0.151591  0.868986  0.046130  3.0
2013-01-05 -1.426182 -0.194032  1.376995  1.332500  4.0
2013-01-06 -1.263439 -0.591865  1.479771  0.658840  5.0

In [112]:
# setting by position
df.iat[0, 1] = 0
df

A         B         C  D    F
2013-01-01  0.000000  0.000000  0.842040  5  NaN
2013-01-02 -0.380125  1.286044 -1.826363  5  1.0
2013-01-03  0.575377 -1.030226 -1.458529  5  2.0
2013-01-04 -0.198816  0.151591  0.868986  5  3.0
2013-01-05 -1.426182 -0.194032  1.376995  5  4.0
2013-01-06 -1.263439 -0.591865  1.479771  5  5.0

In [114]:
# setting by assigning with a NumPy array :
len(df)  # num of rows
df.loc[:, 'D'] = np.array([5] * len(df)) # [5, 5, 5, 5, 5, 5]
df

A         B         C  D    F
2013-01-01  0.000000  0.000000  0.842040  5  NaN
2013-01-02 -0.380125  1.286044 -1.826363  5  1.0
2013-01-03  0.575377 -1.030226 -1.458529  5  2.0
2013-01-04 -0.198816  0.151591  0.868986  5  3.0
2013-01-05 -1.426182 -0.194032  1.376995  5  4.0
2013-01-06 -1.263439 -0.591865  1.479771  5  5.0

In [116]:
############################################
# Missing Data
############################################

# pandas primarily uses the value 'np.nan' ro represent missing data.
# it is by default not included computations.

# Reindecing allows you to  change/add/delete the index on a specified
# axis. this returns a copy of the data

df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ['E'])
df1.loc[dates[0]:dates[1], 'E'] = 1
df1

A         B         C  D    F    E
2013-01-01  0.000000  0.000000  0.842040  5  NaN  1.0
2013-01-02 -0.380125  1.286044 -1.826363  5  1.0  1.0
2013-01-03  0.575377 -1.030226 -1.458529  5  2.0  NaN
2013-01-04 -0.198816  0.151591  0.868986  5  3.0  NaN

In [118]:
# to drop any rows that have missing data
df1.dropna(how='any')

A         B         C  D    F    E
2013-01-02 -0.380125  1.286044 -1.826363  5  1.0  1.0

In [120]:
# Filling missing data
df1.fillna(value=5)

A         B         C  D    F    E
2013-01-01  0.000000  0.000000  0.842040  5  5.0  1.0
2013-01-02 -0.380125  1.286044 -1.826363  5  1.0  1.0
2013-01-03  0.575377 -1.030226 -1.458529  5  2.0  5.0
2013-01-04 -0.198816  0.151591  0.868986  5  3.0  5.0

In [122]:
# To get the boolean mask where values are nan
pd.isna(df1)

A      B      C      D      F      E
2013-01-01  False  False  False  False   True  False
2013-01-02  False  False  False  False  False  False
2013-01-03  False  False  False  False  False   True
2013-01-04  False  False  False  False  False   True

In [123]:
# applying functions to the data

df.apply(np.cumsum)

A         B         C   D     F
2013-01-01  0.000000  0.000000  0.842040   5   NaN
2013-01-02 -0.380125  1.286044 -0.984323  10   1.0
2013-01-03  0.195251  0.255818 -2.442852  15   3.0
2013-01-04 -0.003564  0.407409 -1.573865  20   6.0
2013-01-05 -1.429746  0.213377 -0.196870  25  10.0
2013-01-06 -2.693185 -0.378488  1.282901  30  15.0

In [124]:
# histogramming
s = pd.Series(np.random.randint(0, 7, size=10))
s

0    5
1    4
2    6
3    4
4    3
5    1
6    0
7    2
8    0
9    3
dtype: int64

In [125]:
s.value_counts()

4    2
3    2
0    2
6    1
5    1
2    1
1    1
dtype: int64

In [126]:
df = pd.DataFrame(np.random.randn(10, 4))
df

0         1         2         3
0  0.156307  2.077708 -0.187990  0.683766
1 -1.355984  1.719081 -0.185957 -1.282808
2 -0.274689  0.151476 -0.618786  0.321699
3 -0.665057 -0.873130 -1.032076 -0.595082
4 -0.965135  1.029279 -1.227946 -1.850264
5 -1.571672  0.139650 -1.897425  0.520509
6  0.167088  1.217712  1.467844 -0.907316
7 -0.147954 -1.235942  1.720112  0.478887
8  0.533746  0.106593 -0.336349  0.501408
9 -0.562698  0.969664  1.088266 -0.451649

In [129]:
pieces = [df[:3], df[3:7], df[7:]]
pieces

[          0         1         2         3
 0  0.156307  2.077708 -0.187990  0.683766
 1 -1.355984  1.719081 -0.185957 -1.282808
 2 -0.274689  0.151476 -0.618786  0.321699,
           0         1         2         3
 3 -0.665057 -0.873130 -1.032076 -0.595082
 4 -0.965135  1.029279 -1.227946 -1.850264
 5 -1.571672  0.139650 -1.897425  0.520509
 6  0.167088  1.217712  1.467844 -0.907316,
           0         1         2         3
 7 -0.147954 -1.235942  1.720112  0.478887
 8  0.533746  0.106593 -0.336349  0.501408
 9 -0.562698  0.969664  1.088266 -0.451649]

In [130]:
pd.concat(pieces)

0         1         2         3
0  0.156307  2.077708 -0.187990  0.683766
1 -1.355984  1.719081 -0.185957 -1.282808
2 -0.274689  0.151476 -0.618786  0.321699
3 -0.665057 -0.873130 -1.032076 -0.595082
4 -0.965135  1.029279 -1.227946 -1.850264
5 -1.571672  0.139650 -1.897425  0.520509
6  0.167088  1.217712  1.467844 -0.907316
7 -0.147954 -1.235942  1.720112  0.478887
8  0.533746  0.106593 -0.336349  0.501408
9 -0.562698  0.969664  1.088266 -0.451649