In [2]:
print('Hello Jupitor')

Hello Jupitor


In [3]:
import numpy as np
import pandas as pd

In [4]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [5]:
dates = pd.date_range('20130101', periods=6, freq='D')
print(dates)
dates2 = pd.date_range('20130101', periods=6, freq='M')
print(dates2)
dates3 = pd.date_range('20130101', periods=6, freq='Y')
print(dates3)

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')
DatetimeIndex(['2013-01-31', '2013-02-28', '2013-03-31', '2013-04-30',
               '2013-05-31', '2013-06-30'],
              dtype='datetime64[ns]', freq='M')
DatetimeIndex(['2013-12-31', '2014-12-31', '2015-12-31', '2016-12-31',
               '2017-12-31', '2018-12-31'],
              dtype='datetime64[ns]', freq='A-DEC')


In [6]:
# Creating a DataFrame by passing a BumPy array, with a datetime index
# and labeled columns

df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
df

A         B         C         D
2013-01-01  0.480811 -2.301358  0.452821 -0.586353
2013-01-02  1.118015 -0.343322 -1.570505  0.374936
2013-01-03 -0.386501 -0.351715  1.419200  1.027139
2013-01-04  1.049505  1.176664 -1.620546 -0.528511
2013-01-05 -0.028976 -0.033604  1.054312 -0.672542
2013-01-06 -0.839519 -0.847511 -1.976500 -2.028791

In [7]:
# Crearting a DataFrame by passing a dict of objects that can be
# converted to series-like
df2 = pd.DataFrame({'A' : 1.,
                    'B' : pd.Timestamp('20130102'),
                    'C' : pd.Series(1, index=list(range(4)), dtype='float32'),
                    'D' : np.array([3] * 4, dtype='int32'),
                    'E' : pd.Categorical(['test', 'train', 'test', 'train']),
                    'F' : 'foo'})
df2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [8]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [9]:
# Here is how to view the top and bottom rows of the frame :
df.head()

A         B         C         D
2013-01-01  0.480811 -2.301358  0.452821 -0.586353
2013-01-02  1.118015 -0.343322 -1.570505  0.374936
2013-01-03 -0.386501 -0.351715  1.419200  1.027139
2013-01-04  1.049505  1.176664 -1.620546 -0.528511
2013-01-05 -0.028976 -0.033604  1.054312 -0.672542

In [10]:
df.tail()

A         B         C         D
2013-01-02  1.118015 -0.343322 -1.570505  0.374936
2013-01-03 -0.386501 -0.351715  1.419200  1.027139
2013-01-04  1.049505  1.176664 -1.620546 -0.528511
2013-01-05 -0.028976 -0.033604  1.054312 -0.672542
2013-01-06 -0.839519 -0.847511 -1.976500 -2.028791

In [11]:
df2.index

Int64Index([0, 1, 2, 3], dtype='int64')

In [12]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [13]:
'''
DataFrame.to_numpy() gives a NumPy representation of the underlying data
Note that this can be ad expensive operation when your DataFrame has columns with different
dtypes, which comes down to a fundemental difference between pandas and NumPy
: Numpy arrays have one dtype for the entire array, whlie pandas DataFrames have one dtype
per column. when you call DataFrame.to_numpy(), pandas will find the Numpy dtype that can hold all of the dtypes in the DataFrame. This may end up being 'object', which requires
casting every value to a Python objent
'''

df.to_numpy()

array([[ 0.4808107 , -2.30135758,  0.45282133, -0.58635313],
       [ 1.11801497, -0.34332246, -1.57050471,  0.37493642],
       [-0.38650134, -0.3517146 ,  1.41920035,  1.02713857],
       [ 1.04950534,  1.17666442, -1.62054594, -0.52851083],
       [-0.02897573, -0.03360371,  1.0543121 , -0.67254188],
       [-0.83951937, -0.84751055, -1.97649952, -2.02879125]])

In [14]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [15]:
# summary of data
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.232222 -0.450141 -0.373536 -0.402354
std    0.789183  1.133667  1.516099  1.040740
min   -0.839519 -2.301358 -1.976500 -2.028791
25%   -0.297120 -0.723562 -1.608036 -0.650995
50%    0.225917 -0.347519 -0.558842 -0.557432
75%    0.907332 -0.111033  0.903939  0.149075
max    1.118015  1.176664  1.419200  1.027139

In [16]:
# Transpose
print(df.to_numpy())
df.T

[[ 0.4808107  -2.30135758  0.45282133 -0.58635313]
 [ 1.11801497 -0.34332246 -1.57050471  0.37493642]
 [-0.38650134 -0.3517146   1.41920035  1.02713857]
 [ 1.04950534  1.17666442 -1.62054594 -0.52851083]
 [-0.02897573 -0.03360371  1.0543121  -0.67254188]
 [-0.83951937 -0.84751055 -1.97649952 -2.02879125]]


2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    0.480811    1.118015   -0.386501    1.049505   -0.028976   -0.839519
B   -2.301358   -0.343322   -0.351715    1.176664   -0.033604   -0.847511
C    0.452821   -1.570505    1.419200   -1.620546    1.054312   -1.976500
D   -0.586353    0.374936    1.027139   -0.528511   -0.672542   -2.028791

In [17]:
# column명을 기준으로 sort
df.sort_index(axis=1, ascending=True)

A         B         C         D
2013-01-01  0.480811 -2.301358  0.452821 -0.586353
2013-01-02  1.118015 -0.343322 -1.570505  0.374936
2013-01-03 -0.386501 -0.351715  1.419200  1.027139
2013-01-04  1.049505  1.176664 -1.620546 -0.528511
2013-01-05 -0.028976 -0.033604  1.054312 -0.672542
2013-01-06 -0.839519 -0.847511 -1.976500 -2.028791

In [18]:
# B column을 기준으로 sort
df.sort_values(by='B', ascending=False)

A         B         C         D
2013-01-04  1.049505  1.176664 -1.620546 -0.528511
2013-01-05 -0.028976 -0.033604  1.054312 -0.672542
2013-01-02  1.118015 -0.343322 -1.570505  0.374936
2013-01-03 -0.386501 -0.351715  1.419200  1.027139
2013-01-06 -0.839519 -0.847511 -1.976500 -2.028791
2013-01-01  0.480811 -2.301358  0.452821 -0.586353

In [19]:
#################################################
# Selection
#################################################

# selection by index (row)

df['A']

2013-01-01    0.480811
2013-01-02    1.118015
2013-01-03   -0.386501
2013-01-04    1.049505
2013-01-05   -0.028976
2013-01-06   -0.839519
Freq: D, Name: A, dtype: float64

In [20]:
df[0:3]

A         B         C         D
2013-01-01  0.480811 -2.301358  0.452821 -0.586353
2013-01-02  1.118015 -0.343322 -1.570505  0.374936
2013-01-03 -0.386501 -0.351715  1.419200  1.027139

In [21]:
df['20130102':'20130104']

A         B         C         D
2013-01-02  1.118015 -0.343322 -1.570505  0.374936
2013-01-03 -0.386501 -0.351715  1.419200  1.027139
2013-01-04  1.049505  1.176664 -1.620546 -0.528511

In [22]:
# selection by label (column)

# dates = ['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04', '2013-01-05', '2013-01-06']
# 2013-01-01 row값을 label을 기준으로 출력
df.loc[dates[0]]

A    0.480811
B   -2.301358
C    0.452821
D   -0.586353
Name: 2013-01-01 00:00:00, dtype: float64

In [23]:
# 전체 row중 'A', 'B' 라벨만을 출력
df.loc[:, ['A', 'B']]

A         B
2013-01-01  0.480811 -2.301358
2013-01-02  1.118015 -0.343322
2013-01-03 -0.386501 -0.351715
2013-01-04  1.049505  1.176664
2013-01-05 -0.028976 -0.033604
2013-01-06 -0.839519 -0.847511

In [24]:
df.loc['20130102':'20130104', ['A', 'B']]

A         B
2013-01-02  1.118015 -0.343322
2013-01-03 -0.386501 -0.351715
2013-01-04  1.049505  1.176664

In [25]:
# for getting a scalar value :
df.loc[dates[0], 'A']

0.4808106961487476

In [26]:
######################################################
# Selection by position
######################################################

# index locating? 인듯
print(df)
df.iloc[3]

A         B         C         D
2013-01-01  0.480811 -2.301358  0.452821 -0.586353
2013-01-02  1.118015 -0.343322 -1.570505  0.374936
2013-01-03 -0.386501 -0.351715  1.419200  1.027139
2013-01-04  1.049505  1.176664 -1.620546 -0.528511
2013-01-05 -0.028976 -0.033604  1.054312 -0.672542
2013-01-06 -0.839519 -0.847511 -1.976500 -2.028791


A    1.049505
B    1.176664
C   -1.620546
D   -0.528511
Name: 2013-01-04 00:00:00, dtype: float64

In [27]:
df.iloc[1:3, :]

A         B         C         D
2013-01-02  1.118015 -0.343322 -1.570505  0.374936
2013-01-03 -0.386501 -0.351715  1.419200  1.027139

In [28]:
df.iloc[[1, 2, 4], [0, 2]]

A         C
2013-01-02  1.118015 -1.570505
2013-01-03 -0.386501  1.419200
2013-01-05 -0.028976  1.054312

In [29]:
# iloc[1, 1], iat[1, 1] 의 결과는 같지만
# iat가 개별 값에 접근할 떄는 더 빠르다

df.iloc[1, 1]

-0.3433224614868818

In [30]:
df.iat[1, 1]

-0.3433224614868818

In [31]:
######################################################
# boolean indexing
######################################################

df[df < 0]

A         B         C         D
2013-01-01       NaN -2.301358       NaN -0.586353
2013-01-02       NaN -0.343322 -1.570505       NaN
2013-01-03 -0.386501 -0.351715       NaN       NaN
2013-01-04       NaN       NaN -1.620546 -0.528511
2013-01-05 -0.028976 -0.033604       NaN -0.672542
2013-01-06 -0.839519 -0.847511 -1.976500 -2.028791

In [32]:
df[df > 0]

A         B         C         D
2013-01-01  0.480811       NaN  0.452821       NaN
2013-01-02  1.118015       NaN       NaN  0.374936
2013-01-03       NaN       NaN  1.419200  1.027139
2013-01-04  1.049505  1.176664       NaN       NaN
2013-01-05       NaN       NaN  1.054312       NaN
2013-01-06       NaN       NaN       NaN       NaN

In [33]:
# column의 추가

df2 = df.copy()
df2['E'] = ['one', 'one', 'two', 'three', 'four', 'three']
df2

A         B         C         D      E
2013-01-01  0.480811 -2.301358  0.452821 -0.586353    one
2013-01-02  1.118015 -0.343322 -1.570505  0.374936    one
2013-01-03 -0.386501 -0.351715  1.419200  1.027139    two
2013-01-04  1.049505  1.176664 -1.620546 -0.528511  three
2013-01-05 -0.028976 -0.033604  1.054312 -0.672542   four
2013-01-06 -0.839519 -0.847511 -1.976500 -2.028791  three

In [34]:
df[df['A'] > 0]

A         B         C         D
2013-01-01  0.480811 -2.301358  0.452821 -0.586353
2013-01-02  1.118015 -0.343322 -1.570505  0.374936
2013-01-04  1.049505  1.176664 -1.620546 -0.528511

In [35]:
df2[df2['E'].isin(['two', 'four'])]

A         B         C         D     E
2013-01-03 -0.386501 -0.351715  1.419200  1.027139   two
2013-01-05 -0.028976 -0.033604  1.054312 -0.672542  four

In [36]:
######################################################
# pandas primarily uses the value 'np.nan' to represent
# missing data. It is by default not included in computations.
# See the missing data selection
######################################################

# reindexing allows you to change / add / delete the index on a 
# specified axis. This returns a copy of the data

df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ['E'])
df1.loc[dates[0]:dates[1], 'E'] = 1
df1

A         B         C         D    E
2013-01-01  0.480811 -2.301358  0.452821 -0.586353  1.0
2013-01-02  1.118015 -0.343322 -1.570505  0.374936  1.0
2013-01-03 -0.386501 -0.351715  1.419200  1.027139  NaN
2013-01-04  1.049505  1.176664 -1.620546 -0.528511  NaN

In [37]:
# to drop any rows that have missing data
df1.dropna(how='any')

A         B         C         D    E
2013-01-01  0.480811 -2.301358  0.452821 -0.586353  1.0
2013-01-02  1.118015 -0.343322 -1.570505  0.374936  1.0

In [38]:
# filling missing data
df1.fillna(value=5)

A         B         C         D    E
2013-01-01  0.480811 -2.301358  0.452821 -0.586353  1.0
2013-01-02  1.118015 -0.343322 -1.570505  0.374936  1.0
2013-01-03 -0.386501 -0.351715  1.419200  1.027139  5.0
2013-01-04  1.049505  1.176664 -1.620546 -0.528511  5.0

In [39]:
# to get the boolean mask where values are nan
pd.isna(df1)

A      B      C      D      E
2013-01-01  False  False  False  False  False
2013-01-02  False  False  False  False  False
2013-01-03  False  False  False  False   True
2013-01-04  False  False  False  False   True

In [40]:
######################################################
# Operation
######################################################

# column 기준
df.mean(False)

A    0.232222
B   -0.450141
C   -0.373536
D   -0.402354
dtype: float64

In [41]:
# row 기준 row기준 = False 가 default 인듯
df.mean(True)

2013-01-01   -0.488520
2013-01-02   -0.105219
2013-01-03    0.427031
2013-01-04    0.019278
2013-01-05    0.079798
2013-01-06   -1.423080
Freq: D, dtype: float64

In [42]:
# shift

s = pd.Series([1, 3, 5, np.nan, 6, 8], index=dates).shift(1)
s

2013-01-01    NaN
2013-01-02    1.0
2013-01-03    3.0
2013-01-04    5.0
2013-01-05    NaN
2013-01-06    6.0
Freq: D, dtype: float64

In [43]:
df.sub(s, axis='index')

A         B         C         D
2013-01-01       NaN       NaN       NaN       NaN
2013-01-02  0.118015 -1.343322 -2.570505 -0.625064
2013-01-03 -3.386501 -3.351715 -1.580800 -1.972861
2013-01-04 -3.950495 -3.823336 -6.620546 -5.528511
2013-01-05       NaN       NaN       NaN       NaN
2013-01-06 -6.839519 -6.847511 -7.976500 -8.028791

In [44]:
df.sub(s, axis='index')

A         B         C         D
2013-01-01       NaN       NaN       NaN       NaN
2013-01-02  0.118015 -1.343322 -2.570505 -0.625064
2013-01-03 -3.386501 -3.351715 -1.580800 -1.972861
2013-01-04 -3.950495 -3.823336 -6.620546 -5.528511
2013-01-05       NaN       NaN       NaN       NaN
2013-01-06 -6.839519 -6.847511 -7.976500 -8.028791

In [45]:
# ######################################################
# Applying function to the data :
######################################################
print(df)
# column별로 cumulative sum
df.apply(np.cumsum)

A         B         C         D
2013-01-01  0.480811 -2.301358  0.452821 -0.586353
2013-01-02  1.118015 -0.343322 -1.570505  0.374936
2013-01-03 -0.386501 -0.351715  1.419200  1.027139
2013-01-04  1.049505  1.176664 -1.620546 -0.528511
2013-01-05 -0.028976 -0.033604  1.054312 -0.672542
2013-01-06 -0.839519 -0.847511 -1.976500 -2.028791


A         B         C         D
2013-01-01  0.480811 -2.301358  0.452821 -0.586353
2013-01-02  1.598826 -2.644680 -1.117683 -0.211417
2013-01-03  1.212324 -2.996395  0.301517  0.815722
2013-01-04  2.261830 -1.819730 -1.319029  0.287211
2013-01-05  2.232854 -1.853334 -0.264717 -0.385331
2013-01-06  1.393335 -2.700844 -2.241216 -2.414122

In [46]:
######################################################
# Histogramming
######################################################

s = pd.Series(np.random.randint(0, 7, size=10))
s

0    6
1    1
2    6
3    0
4    6
5    2
6    3
7    1
8    5
9    2
dtype: int64

In [47]:
s.value_counts()

6    3
2    2
1    2
5    1
3    1
0    1
dtype: int64

In [48]:
s.value_counts().sort_index()

0    1
1    2
2    2
3    1
5    1
6    3
dtype: int64

In [49]:
s = pd.Series(['apple', 'Banan', 'Carrot', 'Aaba', 'Bcad', np.nan, 'CABA'])
s.str.lower()

0     apple
1     banan
2    carrot
3      aaba
4      bcad
5       NaN
6      caba
dtype: object

In [50]:
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [51]:
############################################
# Setting 
############################################
# Setting a new column automatically aligns the data by the indices

s1 = pd.Series([1, 2, 3, 4, 5, 6], index=pd.date_range('20130102', periods=6))
s1

2013-01-02    1
2013-01-03    2
2013-01-04    3
2013-01-05    4
2013-01-06    5
2013-01-07    6
Freq: D, dtype: int64

In [52]:
df

A         B         C         D
2013-01-01  0.480811 -2.301358  0.452821 -0.586353
2013-01-02  1.118015 -0.343322 -1.570505  0.374936
2013-01-03 -0.386501 -0.351715  1.419200  1.027139
2013-01-04  1.049505  1.176664 -1.620546 -0.528511
2013-01-05 -0.028976 -0.033604  1.054312 -0.672542
2013-01-06 -0.839519 -0.847511 -1.976500 -2.028791

In [53]:
# df에 F column으로 s1을 추가


In [54]:
# 1월2일부터 해당 값이 자동으로 setting되어 입력된다

df['F'] = s1
df

A         B         C         D    F
2013-01-01  0.480811 -2.301358  0.452821 -0.586353  NaN
2013-01-02  1.118015 -0.343322 -1.570505  0.374936  1.0
2013-01-03 -0.386501 -0.351715  1.419200  1.027139  2.0
2013-01-04  1.049505  1.176664 -1.620546 -0.528511  3.0
2013-01-05 -0.028976 -0.033604  1.054312 -0.672542  4.0
2013-01-06 -0.839519 -0.847511 -1.976500 -2.028791  5.0

In [55]:
# setting values by label
df.at[dates[0], 'A'] = 0
df

A         B         C         D    F
2013-01-01  0.000000 -2.301358  0.452821 -0.586353  NaN
2013-01-02  1.118015 -0.343322 -1.570505  0.374936  1.0
2013-01-03 -0.386501 -0.351715  1.419200  1.027139  2.0
2013-01-04  1.049505  1.176664 -1.620546 -0.528511  3.0
2013-01-05 -0.028976 -0.033604  1.054312 -0.672542  4.0
2013-01-06 -0.839519 -0.847511 -1.976500 -2.028791  5.0

In [56]:
# setting by position
df.iat[0, 1] = 0
df

A         B         C         D    F
2013-01-01  0.000000  0.000000  0.452821 -0.586353  NaN
2013-01-02  1.118015 -0.343322 -1.570505  0.374936  1.0
2013-01-03 -0.386501 -0.351715  1.419200  1.027139  2.0
2013-01-04  1.049505  1.176664 -1.620546 -0.528511  3.0
2013-01-05 -0.028976 -0.033604  1.054312 -0.672542  4.0
2013-01-06 -0.839519 -0.847511 -1.976500 -2.028791  5.0

In [57]:
# setting by assigning with a NumPy array :
len(df)  # num of rows
df.loc[:, 'D'] = np.array([5] * len(df)) # [5, 5, 5, 5, 5, 5]
df

A         B         C  D    F
2013-01-01  0.000000  0.000000  0.452821  5  NaN
2013-01-02  1.118015 -0.343322 -1.570505  5  1.0
2013-01-03 -0.386501 -0.351715  1.419200  5  2.0
2013-01-04  1.049505  1.176664 -1.620546  5  3.0
2013-01-05 -0.028976 -0.033604  1.054312  5  4.0
2013-01-06 -0.839519 -0.847511 -1.976500  5  5.0

In [58]:
############################################
# Missing Data
############################################

# pandas primarily uses the value 'np.nan' ro represent missing data.
# it is by default not included computations.

# Reindecing allows you to  change/add/delete the index on a specified
# axis. this returns a copy of the data

df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ['E'])
df1.loc[dates[0]:dates[1], 'E'] = 1
df1

A         B         C  D    F    E
2013-01-01  0.000000  0.000000  0.452821  5  NaN  1.0
2013-01-02  1.118015 -0.343322 -1.570505  5  1.0  1.0
2013-01-03 -0.386501 -0.351715  1.419200  5  2.0  NaN
2013-01-04  1.049505  1.176664 -1.620546  5  3.0  NaN

In [59]:
# to drop any rows that have missing data
df1.dropna(how='any')

A         B         C  D    F    E
2013-01-02  1.118015 -0.343322 -1.570505  5  1.0  1.0

In [60]:
# Filling missing data
df1.fillna(value=5)

A         B         C  D    F    E
2013-01-01  0.000000  0.000000  0.452821  5  5.0  1.0
2013-01-02  1.118015 -0.343322 -1.570505  5  1.0  1.0
2013-01-03 -0.386501 -0.351715  1.419200  5  2.0  5.0
2013-01-04  1.049505  1.176664 -1.620546  5  3.0  5.0

In [61]:
# To get the boolean mask where values are nan
pd.isna(df1)

A      B      C      D      F      E
2013-01-01  False  False  False  False   True  False
2013-01-02  False  False  False  False  False  False
2013-01-03  False  False  False  False  False   True
2013-01-04  False  False  False  False  False   True

In [62]:
# applying functions to the data

df.apply(np.cumsum)

A         B         C   D     F
2013-01-01  0.000000  0.000000  0.452821   5   NaN
2013-01-02  1.118015 -0.343322 -1.117683  10   1.0
2013-01-03  0.731514 -0.695037  0.301517  15   3.0
2013-01-04  1.781019  0.481627 -1.319029  20   6.0
2013-01-05  1.752043  0.448024 -0.264717  25  10.0
2013-01-06  0.912524 -0.399487 -2.241216  30  15.0

In [63]:
# histogramming
s = pd.Series(np.random.randint(0, 7, size=10))
s

0    4
1    2
2    5
3    0
4    4
5    4
6    5
7    6
8    1
9    4
dtype: int64

In [64]:
s.value_counts()

4    4
5    2
6    1
2    1
1    1
0    1
dtype: int64

In [65]:
df = pd.DataFrame(np.random.randn(10, 4))
df

0         1         2         3
0 -0.203491  0.373586 -1.256488 -0.043137
1 -1.930230 -0.649066  0.710945  0.562607
2 -2.038120  1.257163 -0.508170 -2.186457
3 -0.980258  0.249704  1.648495 -0.437753
4  0.576783 -1.740723  0.562328 -0.622344
5 -1.093836  1.049765  0.392890  0.340789
6  1.253931 -1.593379 -1.008994  0.064869
7  2.906345 -1.644633 -1.914596 -1.084555
8  0.588261 -0.301940  1.939013  0.065548
9  1.007816  0.985344  0.007301  0.473119

In [66]:
pieces = [df[:3], df[3:7], df[7:]]
pieces

[          0         1         2         3
 0 -0.203491  0.373586 -1.256488 -0.043137
 1 -1.930230 -0.649066  0.710945  0.562607
 2 -2.038120  1.257163 -0.508170 -2.186457,
           0         1         2         3
 3 -0.980258  0.249704  1.648495 -0.437753
 4  0.576783 -1.740723  0.562328 -0.622344
 5 -1.093836  1.049765  0.392890  0.340789
 6  1.253931 -1.593379 -1.008994  0.064869,
           0         1         2         3
 7  2.906345 -1.644633 -1.914596 -1.084555
 8  0.588261 -0.301940  1.939013  0.065548
 9  1.007816  0.985344  0.007301  0.473119]

In [67]:
pd.concat(pieces)

0         1         2         3
0 -0.203491  0.373586 -1.256488 -0.043137
1 -1.930230 -0.649066  0.710945  0.562607
2 -2.038120  1.257163 -0.508170 -2.186457
3 -0.980258  0.249704  1.648495 -0.437753
4  0.576783 -1.740723  0.562328 -0.622344
5 -1.093836  1.049765  0.392890  0.340789
6  1.253931 -1.593379 -1.008994  0.064869
7  2.906345 -1.644633 -1.914596 -1.084555
8  0.588261 -0.301940  1.939013  0.065548
9  1.007816  0.985344  0.007301  0.473119

In [68]:
# Join 
# SQL style merges, See the Database style joining section.

left  = pd.DataFrame({'key' : ['foo', 'foo'], 'lval' : [1, 2]})
right = pd.DataFrame({'key' : ['foo', 'foo'], 'rval' : [4, 5]})
print(left)
print(right)

key  lval
0  foo     1
1  foo     2
   key  rval
0  foo     4
1  foo     5


In [69]:
pd.merge(left, right, on='key')

key  lval  rval
0  foo     1     4
1  foo     1     5
2  foo     2     4
3  foo     2     5

In [71]:
left  = pd.DataFrame({'key' : ['foo', 'bar'], 'lval' : [1, 2]})
right = pd.DataFrame({'key' : ['foo', 'bar'], 'rval' : [4, 5]})
pd.merge(left, right, on='key')

key  lval  rval
0  foo     1     4
1  bar     2     5

In [72]:
#################################
# Grouping
#################################


In [73]:
# By "group by" we are referring to a process involving one or more of the following steps ;
# - splitting the data into groups based on some criteria
# - Applying a function to each group independently
# - Combining the results into a data structure

df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                          'foo', 'bar', 'foo', 'bar'],
                   'B' : ['one', 'one', 'two', 'three',
                          'two', 'two', 'one', 'three'],
                   'C' : np.random.randn(8),
                   'D' : np.random.randn(8)})
df

A      B         C         D
0  foo    one  0.337530 -1.124641
1  bar    one  1.778119 -1.337290
2  foo    two -0.810535 -0.297194
3  bar  three -0.361241 -0.593613
4  foo    two -0.528152  0.558360
5  bar    two  1.159578 -0.456980
6  foo    one -0.260407  0.072617
7  bar  three  0.746764 -2.147137

In [75]:
# Grouping and then applying the sum() function to the resulting groups
df.groupby('A').sum()

C         D
A                      
bar  3.323221 -4.535020
foo -1.261564 -0.790859

In [83]:
df[df['A'] == 'bar'].sum()

A        barbarbarbar
B    onethreetwothree
C             3.32322
D            -4.53502
dtype: object

In [85]:
df.groupby(['A', 'B']).sum()

C         D
A   B                        
bar one    1.778119 -1.337290
    three  0.385523 -2.740750
    two    1.159578 -0.456980
foo one    0.077123 -1.052024
    two   -1.338687  0.261165

In [ ]:
#################################
# Reshaping
#################################

tuples = list(zip(*[['bar', 'bar', 'baz', 'baz',
                     'foo', 'foo', 'qux', 'qux'],
                    ['one', 'two', 'one', 'two',
                     'one', 'twp', 'one', 'two']]))
index = pd.MultiIndex.from_tuples(tuples, name=['first', 'second'])